irc:
  connection: irc://user:pass@irc.freenode.net:6697
  channels: ["#amphp"]

plugins:
  Kelunik\Mellon\Plugins\GitHubEvents:
    githubClientId: ...
    githubClientSecret: ...
    twitterConsumerKey: ...
    twitterConsumerSecret: ...
    twitterAccessToken: ...
    twitterAccessTokenSecret: ...
    interval: 5
    channels:
      "#amphp": amphp
  Kelunik\Mellon\Plugins\Canon:
    channelAdmins:
      "#amphp": [kelunik, bwoebi, trowski]