mail:
  username: ...
  password: ...

telegram:
  auth: ...
  chat: ...

github:
  clientId: ...
  clientSecret: ...

twitter:
  consumerKey: ...
  consumerSecret: ...
  accessToken: ...
  accessTokenSecret: ...